[tool.flake8]
max-line-length = 120
exclude = [
    ".git",
    "__pycache__",
    "docs/source/conf.py",
    "build",
    "dist",
    "tests",
    "alembic"
]
ignore = [
    "I101",
    "D100",
    "D101",
    "D102",
    "D103",
    "D104",
    "D105",
    "D107",
    "D401",
    "E203",
    "I900",
    "N802",
    "N806",
    "N812",
    "W503",
    "S311",
    "S605",
    "S607",
    "ISC003",
    "ISC001",
    "T101",
    "T000",
    "F541",
    "PL123",
    "E712"
]
per-file-ignores = [
    '__init__.py:F401',
]

[tool.mypy]
ignore_missing_imports = true
disallow_untyped_defs = true
check_untyped_defs = true
warn_redundant_casts = true
no_implicit_optional = true
strict_optional = true
show_error_codes = true
strict_equality = true
warn_unreachable = true
warn_unused_configs = true
